services:
  postgres:
    image: postgres:16-alpine
    container_name: interviewx_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tushar
      POSTGRES_DB: interviewx
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: interviewx_backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:tushar@postgres:5432/interviewx
      JWT_SECRET: supersecretkey
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    container_name: interviewx_frontend
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_GRAPHQL_URL: http://localhost:4000/graphql
    ports:
      - "3000:3000"

volumes:
  postgres_data:
